In [1]:
import numpy as np
a  = np.array([(x , y) for x in range(6) for y in range(6)])
a

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [0, 5],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [2, 5],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [3, 5],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [4, 5],
       [5, 0],
       [5, 1],
       [5, 2],
       [5, 3],
       [5, 4],
       [5, 5]])

In [2]:
b = a.reshape([6, 6, 2])
b

array([[[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5]],

       [[1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5]],

       [[2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5]],

       [[3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5]],

       [[4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5]],

       [[5, 0],
        [5, 1],
        [5, 2],
        [5, 3],
        [5, 4],
        [5, 5]]])

In [3]:
b.shape()

TypeError: 'tuple' object is not callable

In [10]:
b = np.array(range(10))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
import tensorflow as tf
tf.layers.conv2d?